### ISSUE TITLE
Returning empty path with missing mandatory route param

### ISSUE THREAD

**Issue by Lansoweb** [zendframework/zend-expressive-fastroute#30]
Hi!
Don't know if I misunderstood but i'm facing a problem with the url view helper.

I have the following route definition:
```php
[
    'name' => 'user',
    'path' => '/user/{id}',
    'middleware' => User\Action\UserAction::class,
    'allowed_methods' => ['GET','POST'],
],
```

If, in a view, I create a link to it like:
```php
<a href="<?= $this->url('user') ?>">Back</a>
```

it returns an empty string, and the button just refresh the page. In this [line](https://github.com/zendframework/zend-expressive-fastroute/blob/master/src/FastRouteRouter.php#L312) the $path is empty.

Shouldn't the helper maybe throw an exception if a mandatory parameter is missing? It not, how the best approach to prevent this? 

I'm glad to provide a PR if an exception is necessary here.

Best Regards,
Leandro

**Comment by michaelmoussa** [comment]
I'd be in favor of throwing an exception in such an occurrence, and it'd probably be worth looking into how `zend-expressive-aurarouter` and `zend-expressive-zendrouter` handle the same situation in order to try to achieve consistency among all three.

I can't think of a use case where I would want to ask for a URL to be generated and be OK with an empty string coming back if I didn't provide enough information for it to be assembled, so I might even consider this behavior a bug. What do you think, @weierophinney ?

**Comment by weierophinney** [comment]
@michaelmoussa Looks like @xtreamwayz may have a fix; @Lansoweb, could you try his patch and see if it corrects the issue for you?

**Comment by weierophinney** [comment]
Forgot to link to the patch: #32.

**Comment by geerteltink** [comment]
@weierophinney A [test is added](https://github.com/zendframework/zend-expressive-fastroute/pull/32/files#diff-7681bcf6cece889cb67c90fa0e32aedeR638) for this issue.

**Comment by Lansoweb** [comment]
@weierophinney Sure. Will try it in a few. Thanks @xtreamwayz

**Comment by Lansoweb** [comment]
@weierophinney @xtreamwayz Worked perfectly! Even discovered other links with missed params in the project already :-)
